export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES'
export const GET_TRENDING_MOVIES_SUCCESS = 'GET_TRENDING_MOVIES_SUCCESS'
export const GET_TRENDING_MOVIES_FAILS = 'GET_TRENDING_MOVIES_FAILS'

export const GET_DISCOVERY_MOVIES = 'GET_DISCOVERY_MOVIES'
export const GET_DISCOVERY_MOVIES_SUCCESS = 'GET_DISCOVERY_MOVIES_SUCCESS'
export const GET_DISCOVERY_MOVIES_FAILS = 'GET_DISCOVERY_MOVIES_FAILS'
